# Generated by Django 6.1.1 on 2026-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(help_text='OPIS Truckstop ID, the identifier used by the price feed.', unique=True)),
                ('name', models.CharField(help_text='Truckstop name. Where the feed spells it several ways for one ID, the longest form is kept.', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(blank=True, help_text='OPIS rack (wholesale pricing region) identifier.', null=True)),
                ('price_per_gallon', models.DecimalField(decimal_places=4, help_text='Retail price per gallon in USD; the mean of all observations for this truckstop.', max_digits=7)),
                ('observation_count', models.PositiveSmallIntegerField(default=1, help_text='How many rows of the source file were averaged into price_per_gallon.')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'fuel station',
                'verbose_name_plural': 'fuel stations',
                'ordering': ('state', 'city', 'name'),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_latlon_idx'), models.Index(fields=['state'], name='station_state_idx'), models.Index(fields=['price_per_gallon'], name='station_price_idx')],
            },
        ),
    ]
